name: Deploy Elias

on:
  push:
    paths-ignore:
      - .github/workflows/deploy.yml
      - README.md
      - .gitignore
      - .terraform.lock.hcl

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan.binary
        env:
          TF_VAR_email: ${{ secrets.EMAIL }}
          TF_VAR_password: ${{ secrets.PASSWORD }}
          TF_VAR_phone_number: ${{ secrets.PHONE }}
          TF_VAR_linkedin: ${{ secrets.LINKEDIN }}
          TF_VAR_github: ${{ secrets.GITHUB }}
          TF_VAR_homepage: ${{ secrets.HOMEPAGE }}

      - name: Show Plan
        run: terraform show -no-color tfplan.binary

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false tfplan.binary
        env:
          TF_VAR_email: ${{ secrets.EMAIL }}
          TF_VAR_password: ${{ secrets.PASSWORD }}
          TF_VAR_phone_number: ${{ secrets.PHONE }}
          TF_VAR_linkedin: ${{ secrets.LINKEDIN }}
          TF_VAR_github: ${{ secrets.GITHUB }}
          TF_VAR_homepage: ${{ secrets.HOMEPAGE }}